version: "3.9"

services:

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: clv_api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: always

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dashboard
    container_name: clv_dashboard
    ports:
      - "8501:8501"
    depends_on:
      - api
    environment:
      - API_BASE_URL=http://api:8000
    volumes:
      - .:/app
    restart: always